docker/1.4.0/Dockerfile.cpu
docker/1.4.0/Dockerfile.gpu

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

add model-server user

---

.github/PULL_REQUEST_TEMPLATE.md
test/integration/local/test_default_model_fn.py
test/integration/local/test_gluon_hosting.py
test/integration/local/test_onnx.py

Fix license header spacing and update PR template

---

docker/1.4.1/Dockerfile.cpu
docker/1.4.1/Dockerfile.eia
docker/1.4.1/Dockerfile.gpu
docker/1.4.1/config.properties
docker/1.4.1/mms-entrypoint.sh

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Upgrade to MXNet 1.4.1 and CUDA 10.0

---

docker/1.4.1/Dockerfile.gpu

Also realized there were some inconsistencies with the CPU Dockerfile, so fixed those as well.

Use mxnet-cu100mkl for GPU image

---

test/conftest.py
test/integration/__init__.py

same as https://github.com/aws/sagemaker-tensorflow-container/pull/199

skip GPU test in regions with limited p2s or p3s

---

buildspec-release.yml

using `$ACCOUNT` was actually the wrong account. we'll need to make the account number configurable in the future if/when different regions have different account numbers, but that will require backend changes first.

change: fix account number in deployment test command

---

buildspec-release.yml
setup.py

the release build was getting throttled for CreateTransformJob calls, so adding retries to mitigate that

change: add retries to remote integ tests in buildspec-release.yml

---

buildspec-release.yml

I forgot about the EI tests in #32 

change: fix account number for EI deployment test in buildspec-release.yml

---

buildspec-release.yml

change: add retries to all integ tests commands in buildspec-release.yml

---

docker/1.4.1/py2/config.properties
docker/1.4.1/py2/dockerd-entrypoint.sh

change: add missing files building MXNet 1.4.1 Python 2 images

---

test/integration/sagemaker/test_elastic_inference.py
tox.ini

Fix flake8.
flake8 passes now.

fix flake8.

---

buildspec-release.yml

Missed a test command in buildspec-release.xml last time, adding the placeholder to it.

fix: add missing placeholder in test for non-eia test command.

---

buildspec-release.yml

Stop interfering with gpu test commands.

change: split cpu and gpu tests for deployments in buildspec-release.yml

---

docker/1.4.1/py3/Dockerfile.eia
docker/1.4.1/py3/mms-entrypoint.py

Create Dockerfile.eia for 1.4.1 with py3, with health check binary included
Tests
- Tested by serving squeezenet model on container.
- Tested with Sagemaker integration tests - "batch_transform.py", " 	test_elastic_inference.py", "test_hosting.py".

New py3 dlc dockerfiles

---

docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py2/dockerd-entrypoint.sh
docker/1.4.1/py2/mms-entrypoint.py

Create Dockerfile.eia for 1.4.1 with py2, with health check binary included
Tests
- Tested by serving squeezenet model on container.
- Tested with Sagemaker integration tests - "batch_transform.py", " 	test_elastic_inference.py", "test_hosting.py".

New py2 dlc dockerfiles

---

buildspec.yml
scripts/build_all.py
scripts/publish_all.py

- add buildspec.yml to enable PR build
- project is already added in cdk package, will run webhub script after buildspec is merged

change: enable PR build

---

buildspec.yml

The spaces between TAG assignment break the build.

fix: correct typo in buildspec

---

scripts/build_all.py

fix: a typo in build_all script

---

docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia

Reverts aws/sagemaker-mxnet-serving-container#64

Revert "Update build context on 1.4.1 EI dockerfiles"

---

buildspec.yml
docker/1.4.1/py2/Dockerfile.cpu
docker/1.4.1/py2/Dockerfile.gpu
scripts/build_all.py
scripts/publish_all.py
src/sagemaker_mxnet_serving_container/serving.py
test/conftest.py

make sure py2 and py3 have consistent build context
- copy container tar file into both docker/py2 and docker/py3
- change cwd to correspondent py version directory
- add eia tests

change: make consistent build context for py versions

---

test/integration/__init__.py

change: update instance type region availability

---

setup.py

https://github.com/aws/sagemaker-inference-toolkit/issues/9
Update the images to take the latest version of sagemaker-inference

Update toolkit version

---

docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia
setup.py

Add comments about sagemaker-inference version comaptible with MMS_VERSION=1.0.5

change: add comments about sagemaker-inference version

---

docker/1.4.1/py2/Dockerfile.eia
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu

Same fix as https://github.com/aws/sagemaker-mxnet-container/pull/122 to get mx serving build working

Pin setuptools in mx serving

---

docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
test/conftest.py
test/integration/sagemaker/test_gluonnlp.py
test/resources/gluonnlp/bert.py

As https://github.com/aws/sagemaker-mxnet-container/pull/124

Add GluonNLP

---

buildspec-deploy.yml
buildspec-release.yml
buildspec.yml
docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
setup.py
tox.ini

feature: Add release to PyPI. Change package name to sagemaker-mxnet-inference.

feature: Add release to PyPI. Change package name to sagemaker-mxnet-inference.

---

docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu

update: Update license URL

---

docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.cpu

remove multi-model label from dockerfiles

change remove multi-model label from dockerfiles

---

README.rst
buildspec-release.yml
buildspec-toolkit.yml
buildspec.yml
docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
test-toolkit/conftest.py
test-toolkit/docker/1.4.1/Dockerfile.dlc.eia
test-toolkit/docker/1.6.0/Dockerfile.mxnet.cpu

* feature: install mxnet-inference toolkit from PyPI.
* infra: do not run dlc tests on toolkit changes.
* infra: run EIA tests for toolkit.

feature: install mxnet-inference toolkit from PyPI.

---

setup.py

upgrade inference-toolkit version to consume this change: https://github.com/aws/sagemaker-inference-toolkit/pull/44

fix: upgrade inference-toolkit version

---

buildspec-toolkit.yml
buildspec.yml

Use tox commands in buildspecs.

infra: use tox in buildspecs

---

buildspec.yml
scripts/build_all.py
scripts/publish_all.py

Reverts aws/sagemaker-mxnet-serving-container#115

Revert "infra: remove unused scripts."

---

test/conftest.py
test/integration/sagemaker/test_gluoncv.py
test/integration/sagemaker/test_gluonnlp.py

There is no GluonCV and GluonNLP for EIA containers which causes it to fail.
Allowing to skip GluonCV and GluonNLP for EIA containers

Skip GluonCV and GluonNLP for EIA containers

---

buildspec-release.yml

infra: fix release build.

---

setup.py
src/sagemaker_mxnet_serving_container/default_inference_handler.py
src/sagemaker_mxnet_serving_container/utils.py
test/unit/test_default_inference_handler.py

* Changed implementation of `default_output_fn`
* Added test to `test_default_inference_handler`

change: Add support for Accept headers with multiple MIME types

---

src/sagemaker_mxnet_serving_container/default_inference_handler.py
test/container/1.7.0/Dockerfile.mxnet.cpu
test/unit/test_default_inference_handler.py

Fix input reshape mismatch issue in default handler for batch transform

Fix input reshape in default handler
