aws/sagemaker-mxnet-inference-toolkit

README.rst

https://github.com/aws/sagemaker-python-sdk/pull/865 contains changes that describe the needed permissions for running EI tests, which is what inspired this PR.

Add link to SageMaker integ test setup requirements to README

---

docker/1.4.1/mms-entrypoint.py

The old entrypoint simply used `$@` in shell, so using quotes in the command like `'mxnet-model-server' '--start' '--mms-config /tmp/foo'` didn't matter, but that kind of list doesn't work with `subprocess.check_call`

Fix shell command in entrypoint

---

docker/1.4.1/Dockerfile.cpu
docker/1.4.1/Dockerfile.gpu

realized I didn't quite address the problem I described in #24, so this PR should do that.
```
$ docker run -it -p 80:8080 -p 8081:8081 preprod-mxnet-serving:1.4.1-cpu-py3
2019-06-21 23:38:01,018 [INFO ] main com.amazonaws.ml.mms.ModelServer -
MMS Home: /usr/local/lib/python3.6/site-packages
Current directory: /
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 2
Max heap size: 128 M
Python executable: /usr/local/bin/python3.6
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Model Store: /opt/ml/model
Initial Models: ALL
Log dir: /logs
Metrics dir: /logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 2
Blacklist Regex: N/A
Maximum Response …
```

Change CMD to emulate old "serve" command

---

buildspec-release.yml

Past me forgot that EI images are CPU-only, and that broke the release build.

change: remove nonexistent EI GPU images from buildspec-release.yml

---

buildspec-release.yml
test/conftest.py

same as https://github.com/aws/sagemaker-mxnet-container/pull/96
*Testing done:*
```
$ pytest test/integration/ --collect-only
======== test session starts ========
[...]
collected 8 items                                                                                                                                                                                                                                                                                                                                                        
<Module test/integration/local/test_default_model_fn.py>
<Function test_default_model_fn[py3-cpu]>
<Function test_default_model_fn_content_type[py3-cpu]>
<Module test/integration/local/test_gluon_hosting.py>
<Function …
```

change: parametrize Python version and processor type in integ tests

---

test/unit/test_default_inference_handler.py
test/unit/test_handler_service.py

pytest returns [`ExceptionInfo` objects](https://docs.pytest.org/en/latest/reference.html#exceptioninfo) instead of the exception itself. pytest 5.0.0 makes those objects respond differently to `str()`, which causes the unit tests to fail with something like:
```
>       assert 'Unsupported model type' in str(e)
E       AssertionError: assert 'Unsupported model type' in '<ExceptionInfo ValueError tblen=2>'
E        +  where '<ExceptionInfo ValueError tblen=2>' = str(<ExceptionInfo ValueError tblen=2>)
```
this is documented in their changelog at https://docs.pytest.org/en/latest/changelog.html:
> #5412: ExceptionInfo objects (returned by pytest.raises) now have the same str representation as repr, which avoids some confusion when users use print(e) to inspect the …

change: update tests to handle pytest's ExceptionInfo change

---

test/integration/sagemaker/test_elastic_inference.py

pytest is spitting out warnings for unregistered marks. I started to register them, but then realized the fixtures are automatically used, so then just tried removing the marks entirely, and things seem to work the same.
*Testing done:*
```
$ pytest -rsx test/integration/sagemaker/test_elastic_inference.py
===== test session starts =====
[...]
collected 1 item
test/integration/sagemaker/test_elastic_inference.py::test_elastic_inference[py3-cpu] SKIPPED          [100%]
===== short test summary info =====
SKIPPED [1] /Users/laurenyu/Documents/workspace/sagemaker-mxnet-serving-container/test/integration/sagemaker/test_elastic_inference.py:33: Skipping because accelerator type was not provided
===== 1 skipped in 0.15 seconds =====
$ pytest -rsx …
```

change: remove unnecessary pytest marks

---

tox.ini

flake8 wasn't really checking docker/ before either, but now there's a Python file in there, so we do need to explicitly configure flake8 to not check the docker/ directory

change: configure flake8 to ignore the docker/ directory

---

scripts/build_all.py

this is a fix for the change in #38 where the EI images are also built according to our old logic. tested the buildspec through local CPU tests in my personal AWS account

change: use Python 2 build logic for EI images during release

---

test/integration/sagemaker/test_elastic_inference.py

The function for skip EIA test is written but it is not been used.
Without these two lines , The Sagemaker 2nd test(test_elastic_inference.py), when used for CPU does not skip with accelerator option given as none.
After the inclusion of these two lines, the codebase of DLC will be shorter.
Have tested it on CPU and EIA instance after making the change in my fork.

Skipping EIA test if accelerator type is None.

---

buildspec-release.yml
test/integration/__init__.py

…ns and no-p3 regions.
Add placeholder in test commands for cpu-instance-type and aws-id
Make the regional release tests work in the new regions.

change: no-p2 regions and no-p3 regions. Add placeholder in test commands for cpu-instance-type and aws-id.

---

docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia

Issue: Building eia dockerfile caused pip error:
```
Traceback (most recent call last):
File "/usr/bin/pip", line 9, in <module>
from pip import main
ImportError: cannot import name main
```
Fix:
- Merging pip upgrade and pip install into a single RUN statement caused pip to not be found.
- Fixed by splitting statement.

separate pip upgrade from other installs

---

docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia

**Issue**
- Build for EIA dockerfiles failed due to different expected build context.
**Fix**
- Modify expected build context w.r.t. sagemaker-mxnet-serving-container distribution, to match existing build instructions on README.
- Also cleaned up Dockerfiles according to Docker best practices.
**Tests**
- Tested images built from these dockerfiles on an EC2 instance with Elastic Inference to serve a model as per instructions at https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-dlc-ec2-mxnet.html

Update build context on 1.4.1 EI dockerfiles

---

buildspec-release.yml

release build cannot find the tar file in py2 build context
copy tar file to docker/py3 and docker/py2 dirs

fix: build context in release build

---

buildspec-release.yml
buildspec.yml
docker/1.4.1/py2/Dockerfile.eia
docker/1.4.1/py3/Dockerfile.eia
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py2/config.properties
docker/1.6.0/py2/mms-entrypoint.py
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
docker/1.6.0/py3/config.properties
docker/1.6.0/py3/mms-entrypoint.py
scripts/build_all.py
scripts/publish_all.py
setup.py
src/sagemaker_mxnet_serving_container/deep_learning_container.py
test/unit/test_deep_learning_container.py
tox.ini

- Release Dockerfiles for 1.6.0 for MXNet Inference containers

Release 1.6.0 Dockerfiles

---

tox.ini

This reverts commit e7fa17b524bb8aabffc541b52a1d5fe95600c200.
Same thing as https://github.com/aws/sagemaker-python-sdk/pull/1229

Revert "change: install python-dateutil explicitly for botocore (#81)"

---

src/sagemaker_mxnet_serving_container/handler_service.py
test/unit/test_handler_service.py

This change modifies the HandlerService to use the `model_dir` from the request context instead of from `sagemaker_inference.environment.model_dir`. This is necessary to support the use of models in different directories but using the default inference handler: https://github.com/aws/sagemaker-inference-toolkit/pull/42

change: Modify HandlerService to use context model_dir

---

setup.py

Upgrade to the latest version of sagemaker-inference: https://github.com/aws/sagemaker-inference-toolkit/releases/tag/v1.2.0

Upgrade the version of sagemaker-inference

---

.coveragerc_py37
buildspec-release.yml
buildspec-toolkit.yml
setup.py
tox.ini

- Upgrade version of sagemaker-inference to `1.3.1`, which supports Python 3.7.
- Update tox and buildspecs to test against py37.
- Update Python version in `setup.py`.

feature: Python 3.7 support

---

docker/1.5.1/py3/Dockerfile.eia

Install latest openssl-1.1.1g from source to fix vulnerabilities raised by dependency-check.

change: Install openssl from source in py3 1.5.1 EI image

---

setup.py

upgrade sagemaker-inference version upper limit to consume this change: https://github.com/aws/sagemaker-inference-toolkit/pull/62

fix: upgrade sagemaker-inference version up to 1.5.2

---

.coveragerc_py38
buildspec-release.yml
buildspec.yml

buildspec-release tests on py27 but some dependent libraries are not maintaining py27 anymore
drop py27 and add py38 support

change: drop py27, add py38 support

---

src/sagemaker_mxnet_serving_container/handler_service.py
test/unit/test_handler_service.py

Inference Failure for MXNet MME Deployment in SageMaker: #135. Added the exception and log to know the issue better.

Add exception for import_module

---

docker/1.5.1/py2/Dockerfile.eia
docker/1.5.1/py3/Dockerfile.eia
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
setup.py
src/sagemaker_mxnet_serving_container/handler_service.py
test/container/1.7.0/Dockerfile.mxnet.cpu

The inference toolkit increases the timeout that the model server waits up to 10 minutes. This change will consume version 1.5.7 which introduces this change.

Bump sm inference toolkit version to 1.5.7

---

docker/1.5.1/py2/Dockerfile.eia
docker/1.5.1/py3/Dockerfile.eia
docker/1.6.0/py2/Dockerfile.cpu
docker/1.6.0/py2/Dockerfile.gpu
docker/1.6.0/py3/Dockerfile.cpu
docker/1.6.0/py3/Dockerfile.gpu
test/container/1.7.0/Dockerfile.mxnet.cpu

Upgrade MMS_VERSION to 1.1.6 in Dockerfiles. MMS 1.1.5 had an issue due to a missing library used for async logging.

fix: Upgrade MMS_VERSION to 1.1.6 in Dockerfiles.

---

setup.py

...remove upper bound to version specification in setup.py
Remove upper bound to version specification of sagemaker-inference in setup.py, to allow upgrades to be pulled in automatically.

fix: stop pinning sagemaker-inference toolkit version
